apiVersion: v1
kind: Service
metadata:
  name: grafana-web
  namespace: monitoring
spec:
  clusterIP: 10.110.255.118
  externalTrafficPolicy: Cluster
  ports:
  - name: nodeport
    nodePort: 32001
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort

